---
- name: Install package manager
  block:
    - name: Install Homebrew
      shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      args:
        creates: /usr/local/bin/brew
      become: yes
      tags: ["package_manager", "homebrew"]
      when: is_mac

    - name: Install Chocolatey
      win_chocolatey:
        name: chocolatey
        state: present
      tags: ["package_manager", "chocolatey"]
      when: is_windows
